### ISSUE TITLE
PressBackground not working

### ISSUE THREAD

**Issue by kosnkow** [EasyAsABC123/Keyboard#3]
I tried with visual studio 2015 (run as administrator), windows 10, sending keys in background application like notepad++ or  wordpad or calculator and it doesn't work. nothing shows in these apps

**Comment by EasyAsABC123** [comment]
Make sure you are compiling your app as x86

Justin Schuhmann

**Comment by kosnkow** [comment]
I am sure, anyway sending background doesn't work, program runs, but reciever in my case notepad++ doesn't recieve anything.

**Comment by EasyAsABC123** [comment]
The pid is likely wrong, I know when I used this I had to send it to a child process of the main app.  Spy++ is your friend

**Comment by TheAlmightyGuru** [comment]
I'm having a similar problem. Built as x86 in VS 2010. BackgroundKeyboardDemo works great at sending all the text to the richtextbox it creates, but it partially fails on some external programs.

In the BackgroundKeyboardDemo source, I commented out the "var procId = Process.GetCurrentProcess().MainWindowHandle;" line and added "var procId = (IntPtr) 0x010A076C;" which is the window handle of an open Cmd window (according to Spy++). This also works just fine. "hello world" is sent followed by an Enter which naturally results in an error, then the Cmd window receives the "sent one key at a time" text.

However, when I run the demo using the window handle of an open Notepad window, I get the "hello world" text from SendChatTextSend(), but it doesn't receive the Enter or the "sent one key at a time" text. Just to be thorough, I tried all three of the window handles of Notepad exposed in Spy++ (title bar, edit, and status bar). Only the Edit window receives text, but it only gets partial text. Anything you could suggest?

**Comment by EasyAsABC123** [comment]
It appears notepad doesn't accept VK_RETURN as a SendMessage, it does accept it in a PostMessage.

Meaning for some reason using:

``` CSharp

            Messaging.SendChatTextPost(notepadTextbox, "hello world!!!");
            Messaging.SendChatTextPost(notepadTextbox, "test!!!");
```

this will work, partly.  `!` is being turned into a 1, and I think SendChatText presses enter twice, one time because the game opened a chat when Enter was pressed...then another after the text. 

In notepad you don't actually need to send the keystrokes individually and can use `WM_SETTEXT`.

I should probably clean this library up so that it is a little cleaner, since a lot of what I just mentioned don't have easy fixes without changing the base library which means it is not as extensible as I would like..

**Comment by TheAlmightyGuru** [comment]
Looks like PostMessage() can handle Enter, but not shift (upper case letters appear as lower and symbols as numbers). I think I can hobble together a way to automate various programs by using SendMessage() for text and symbols, and then PostMessage() for special keys like enter and tab, but I'll keep an eye on this if you rework it!

**Comment by tobster-de** [comment]
This code has some issues (unessecary recursions e.g.). The one you are referring to is the mismatch of the shift key codes. I tried to refactor it but got near a complete rewrite and it's even not working correctly yet. I finally gave up. (I'm about to use [InputSimulator](https://www.nuget.org/packages/InputSimulator/1.0.4)).

Nevermind: According to [MSDN](https://msdn.microsoft.com/en-us/library/ms646329.aspx) shift values are as follows:

```
[Serializable, Flags]
public enum ShiftType
{
     NONE = 0x0,
     SHIFT = 0x1,
     CTRL = 0x2,
     SHIFT_CTRL = SHIFT | CTRL,
     ALT = 0x4,
     SHIFT_ALT = ALT | SHIFT,
     CTRL_ALT = CTRL | ALT,
     SHIFT_CTRL_ALT = SHIFT | CTRL | ALT
}
```

In [Messaging.cs](https://github.com/EasyAsABC123/Keyboard/blob/master/Keyboard/Messaging.cs#L372) ALT is mistaken with SHIFT. I hope this helps a bit.

**Comment by EasyAsABC123** [comment]
You can't use post message or send message to do any of those system keys.

Only the keyboard which effects the global keyboard works on that

**Comment by EasyAsABC123** [comment]
updated codes

**Comment by IneedHelp** [comment]
Unfortunately

```
var key = new Key(Messaging.VKeys.KEY_1);            
var success = key.PressBackground(hWnd: windowHandle);
```
still doesn't work : (

Trying to send keys to notepad2 using a 64-bit application.

**Comment by EasyAsABC123** [comment]
Sure the code that picks the hwnd

**Comment by IneedHelp** [comment]
Yes, the *hwnd* is good because it works when used with *PressForeground* (although it only works if the window is not minimized, only if it's in the background or focused), but *PressBackground* has no effect (no matter what state the window is in: minimized, in the background or focused), yet it returns *true*.

**Comment by EasyAsABC123** [comment]
They work differently and forgive works with any hwnd in the process at all
background doesn't

**Comment by IneedHelp** [comment]
So it's possible that it might not work at all? What other *hwnd* can I get for background than the window *hwnd*?

**Comment by EasyAsABC123** [comment]
The textarea hwnd, you can find this with Spy++

**Comment by IneedHelp** [comment]
I understand, thank you for the help.

**Comment by IneedHelp** [comment]
One more question regarding `PressBackground`, is it known that application developed with https://electronjs.org/ like Discord and Spotify don't accept any messages when not focused?

Because I am trying it with Discord and Spotify and it doesn't  when using `PressBackground` and this time I'm getting the correct window handles, there's just 2 of them:
![image](https://i.imgur.com/ohQJeQW.png)

However, `PressBackground` does work on them if the windows are in focus.

**Comment by EasyAsABC123** [comment]
This might not work with all apps it was developed for aion online and I
just decided why not share it.  Definitely no guarantees about all apps.
Background keypresses aren't the simplistic items there are.  If you need a
fool proof method you'd want to dll inject a keyboard hook that manages
keyboard state.  Then it needs to have an api that listens for messages and
injects the keys onto the keyboard state

**Comment by IneedHelp** [comment]
I understand. Thank you for the information.
